# Generated by Django 3.1.8 on 2022-07-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_auto_20220706_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
