# Generated by Django 3.1.8 on 2022-07-19 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0006_auto_20220720_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminallog',
            name='criminal_profile_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recognition.criminal_profile'),
        ),
        migrations.AlterField(
            model_name='criminallog',
            name='alias_name',
            field=models.CharField(max_length=30),
        ),
    ]
