# Generated by Django 3.1.8 on 2022-07-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0007_auto_20220720_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminallog',
            name='criminal_profile_link',
        ),
    ]
