# Generated by Django 3.1.8 on 2022-07-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0008_remove_criminallog_criminal_profile_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CriminalLog',
        ),
    ]
