# Generated by Django 3.1.8 on 2022-07-19 22:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0009_delete_criminallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('alias_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.criminal_profile', to_field='alias_name')),
            ],
        ),
    ]
