# Generated by Django 3.1.8 on 2022-07-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0010_criminallog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminallog',
            old_name='alias_name',
            new_name='criminal_profile_link',
        ),
    ]
