# Generated by Django 3.1.8 on 2022-07-21 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0011_auto_20220720_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminallog',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
